### ISSUE TITLE
Error on parse lang code

### ISSUE THREAD

**Issue by Illia-M** [bartfeenstra/betty#2184]
Hi! I use Place Cleanup gramplet in Gramps to find places from GeoNames. Usually I same alternative names for places and some times "all names that I see" so can be stored not standard language codes or it can be code out of ISO like old russian writing style used in Ukraine under Russian Empire. So - I can not generate tree) Get error, like on screen

![image](https://github.com/user-attachments/assets/60dd5a76-b52e-4d25-91e6-86b350bc3809)

Is it should be in such way? Or should such entities be skipped?

**Comment by bartfeenstra** [comment]
The way locale handling works in Betty (and the majority of software), is that we use libraries that are ultimately provided by the operating system. This is because handling locales correctly is complex and requires quite a bit of diskspace for metadata. As a consequence, the total set of locales available to Betty is limited to what the system Betty runs on supports. Any time Betty encounters a language code, it validates it against this set of supported locales.

The problem you ran into was bound to happen at some point, because Betty simply raises an error when a locale is not supported by the system. The question is how Betty should handle these cases. It looks like in your case, the error comes from `betty.locale.localizable.assertion.assert_static_translations()` (based on the `data` context, and static translations are mappings with locales as keys). These static translations are used throughout Betty, in configuration files, as well as on entities, so we need a rather generic and graceful solution.

I propose that when parsing static translations through `assert_static_translations()`, it simply ignores unknown locales, and raises a warning for them.
Pros: data that is automatically imported from an otherwise perfectly valid Gramps family tree will no longer cause fatal errors
Cons: in cases where the locale **should** be corrected, such as in a Betty project configuration file, a warning will be slightly less useful than the current error, because the error contains context information we cannot add to warnings (other than to hardcode them into the message string, but that's not a precedent I'd like to set).

**Comment by bartfeenstra** [comment]
I just opened https://github.com/bartfeenstra/betty/pull/2186. Can you that PR by installing Betty using `pip install git+https://github.com/bartfeenstra/betty.git@allow-unsupported-locales`, and see how that works for your Gramps family tree?

Note that the aforementioned issue of software using system libraries for locale handling applies everywhere, including to visitors of your site. For example, if your site includes text in locales, or specifically (writing) **scripts** that do not exist on visitors' systems (or for which no fonts exist), their browsers may not be able to render the text. That's a generic limitation of computers and the web, though.

**Comment by Illia-M** [comment]
It works, but fail in other step, you can see in my test repo
https://github.com/Illia-M/test-betty-tree/actions/runs/11649767464/job/32437676231

**Comment by bartfeenstra** [comment]
Ah, that's a different bug, so let's tackle that separately. From what I can tell it should be a quick fix.
