### ISSUE TITLE
Places : Place type not captured

### ISSUE THREAD

**Issue by unixmiddleware** [bartfeenstra/betty#640]
With regards places, unless I'm mistaken (always possible) the 'type' of place isn't captured in _parse_place.
The element that's passed has the attributes shown in the attached png file.
If I'm right, and it's not captured elsewhere, would you mind adding it please?
The reason I want it is because, using nominatim, there are 10 Irelands!

0, type: administrative, display_name: Éire / Ireland
1, type: island, display_name: Ireland
2, type: hamlet, display_name: Ireland, Old Warden, Central Bedfordshire, East of England, England, SG17 5QL, United Kingdom
3, type: hamlet, display_name: Ireland, Dubois County, Indiana, 47545, United States of America
4, type: hamlet, display_name: Ireland, Lewis County, West Virginia, 26376, United States of America
5, type: hamlet, display_name: Ireland, Bigton, Shetland Islands, Scotland, ZE2 9JA, United Kingdom
6, type: hamlet, display_name: Ireland, Coryell County, Texas, United States of America
7, type: isolated_dwelling, display_name: Ireland, Balhall, Angus, Scotland, DD9 7UL, United Kingdom
8, type: hamlet, display_name: Ireland, Athens County, Ohio, United States of America
9, type: hamlet, display_name: Ireland, Landaff, Grafton County, New Hampshire, United States of America

I want to refine the nominatim query to say type 'island' when the gramps attribute is 'Country', and probably similar for other gramps place types.
![place-type](https://user-images.githubusercontent.com/14218167/101281886-a28c7400-37c9-11eb-9421-fb34bcc0e0df.png)

**Comment by bartfeenstra** [comment]
Thanks for opening this issue! It's something I've wanted to add to Betty, but don't really know how to solve well. contemporary addresses are difficult enough (a common problem in e-commerce software), but for software that must be able to handle historical place descriptions *and* describe these in contemporary concepts, that's an even harder problem to solve.

## Examples
- Are French *provinces*, Canadian *provinces*, Dutch *provincies*, and Roman *provinciae* the same? The ones in the Netherlands and France are most similar in terms of limited autonomy and administrative responsibilities, whereas the Canadian and Roman ones are much more autonomous, despite sharing the same etymological name.
- Are Polish *województwa* comparable to French or Dutch provinces, or British *counties*, because they are the administrative subdivision directly below the national government? If yes, are they still comparable considering the fact that województwa contain  *powiaty*, which are also comparable to British counties?
- The Netherlands has not made any legal distinction between cities, towns, villages, hamlets, or parishes for over 200 years. When this system was introduced, the existing subdivisions at the time were all converted to *gemeentes*. Some subdivisions fit into the new system exactly as they were, and others changed or merged.

I hope these examples illustrate how introducing place types across jurisdictions and time is not an easy thing to get right, especially because the kind of service you are trying to integrate Betty with (and other developers might want to integrate Betty with in the future) expects some unified form of classifying places.

## Proposal
I do believe there may be a few concepts common across the world that we can start with:
- Sovereign entities: countries or regions that do not fall below any other entities.
- Non-sovereign administrative subdivisions: gemeentes, counties, województwa, cities, villages, etc. Some of these are localities or settlements.
- Non-sovereign non-administrative subdivisions: neighborhoods, streets, etc.
- Buildings or plots, identified by names, numbers, or arbitrary descriptions such as "the blue house on the main road".
- Units within a building or on a plot: "flat 5", "bungalow C", etc.
- Geographical features: "the Forbidden Forest", "the third hill past the mountain range", "on the northern end of the great lake".

**Comment by bartfeenstra** [comment]
@unixmiddleware I just opened https://github.com/bartfeenstra/betty/issues/640 which should add everything to load Gramps' built-in place types as well as allow users to override or extend this default mapping.
