### ISSUE TITLE
Clarification of "static site generator"

### ISSUE THREAD

**Issue by emyoulation** [bartfeenstra/betty#925]
Betty is described as a creating a Static Site. Could you clarify that? 

Does it do the same thing as Gramps' built-in "Narrated Web Site Report" ... pre-builds a webpage for every navigable node of the Tree? But does Betty do this on the Server-side when the XML is uploaded? (As opposed to on-the-desktop which results in needing to do a massive FTP transfer of the complete website.)

Or does Betty Server-side generate pages (on demand) from the XML?

**Comment by bartfeenstra** [comment]
Gramps' Narrated Web Site Report is indeed also a statically generated site, like any Betty site. You can do this anywhere you want: on a remote server using the CLI, or on your own machine using the CLI or the desktop GUI application.

Betty is not limited to just processing Gramps data. What happens when generating a site is that all the inputs are parsed and loaded into Betty's data model through `Loader` extensions, of which `betty.gramps.Gramps` is currently the only implementation shiped with Betty.

Betty then allows for processing of that data depending on your project's configuration: guard privacy, derive additional data, and clean up orphan data.

Finally, the resulting data (family tree) is built into HTML pages and JSON files (for the HTTP API), images are resized, CSS and JS files are compiled, etc.

The output of this generation is a www/public directory with the site that can be viewed locally or, copied to a flash drive, or uploaded through rsync/scp/FTP/etc.

At this point, all you need is a web browser to view the site, and any off-the-shelf webserver or web host to publish the site online. Because the site is static, no additional software is required (PHP, Python, databases...) for this.

**Comment by bartfeenstra** [comment]
@emyoulation Hiya! Was this helpful or do you have more questions?

**Comment by emyoulation** [comment]
Yes, it was helpful. Thank you!

(But I always have more questions. I am a never-ending fount of curiosity.)

**Comment by bartfeenstra** [comment]
Wonderful. I'll just close this to keep the issue queue tidy. Feel free to come back with more questions or ideas :)

**Comment by emyoulation** [comment]
Great. 

Expanded the [Betty section on the Gramps-project wiki](https://gramps-project.org/wiki/index.php/Web_Solutions_for_Gramps#Betty) based on the information.

**Comment by bartfeenstra** [comment]
Thanks!
