### ISSUE TITLE
Betty.app doesn't open on M1

### ISSUE THREAD

**Issue by Sternbach-Software** [bartfeenstra/betty#993]
I was about to give up on trying to get Betty working when I was looking through the closed issues and found mention of a betty app for MacOS. The links in that issue were dead, but I looked in the releases page and found the .app file. After allowing the file in security settings, it wouldn't open. I tried installing with `pip install betty`, but python is not my native language, and `whereis betty` did not return anything, so I have no idea how to follow the directions. I don't use Linux, so I can't build from source. As of now, I am out of luck.

**Comment by bartfeenstra** [comment]
Hi there! Thanks for stopping by.
- Betty doesn't have to be compiled from source (Python is not that kind of language), so `pip install betty` is the most low-level you can go.
- It appears you [ran into an error](https://github.com/bartfeenstra/betty/issues/994) saying `npm` did not exist in your system. That's if you want to use the Trees, Maps, or HttpApiDoc extensions. You can disable those so npm is no longer required, or install [Node.js](https://nodejs.org/) (which comes with `npm`) in order to use those extensions.

If you have any further problems, please feel free to open new issues and include as many details as you can provide.
